name: XCTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/* ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: xcodebuild test -project football.xcodeproj/ -scheme football -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"

